### ISSUE TITLE
User input options

### ISSUE THREAD

**Issue by HoveringTorso** [margosij/Project1#3]
Add the following elements to the sticky navbar:
- Navbar brand header text
- Category dropdown with options (Any, Programming, Miscellaneous)
- Type dropdown with options ("One-liner", "Setup/Punchline")
- Button to "Get Joke"

**Comment by kimocreary** [comment]
sounds good!

**Comment by HoveringTorso** [comment]
Are the "category" and "type" dropdowns still necessary for our use of the new joke API? And if so, would they still need the same dropdown options in them? Are there any new user input options we should account for with the new API?

**Comment by HoveringTorso** [comment]
Closing as resolved. Dropdowns no longer necessary for the new joke api we're using.
